### PR TITLE
Initial Profile Page, REST API, & Ui Fixes

### PR DESCRIPTION
**Pull request by KarlDorogy**
# Description

Please include a summary of the changes and issues that were fixed. Please also include relevant context. List any dependencies that are required for this change.

- Created REST API to connect Frontend to Backend along
-  Created Lambda functions to create user, update user, read user, create group, and execute scope1&2Calculations
- Added authentication to amplify profile page & home page
- Updated Navbar & Sidebar to change based on user sign-in status
- Create a Profile page
- Create an initial placeholder Homepage for dev testing/use

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# (If Applicable) How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by JoshQU — APPROVED** [review]
Initial sign in and create account ui looks great. Running locally, the current ui works well for any screen size. 👍

**Review by DouglasChafee — APPROVED** [review]
everything works and looks good

**Review by BriggsFisher — APPROVED** [review]
New API works as intended and the profile page UI is a good base for starting work on the creating groups function.

**Review by To-m-L — APPROVED** [review]
looks good

**Pull request merged**
