### PR TITLE
Contact

### PR DESCRIPTION
**Pull request by To-m-L**
# Description

Created the contact page, which shows the emails, phone number(s), and address for customers to refer to if they need help.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# (If Applicable) How Has This Been Tested?

I looked at it

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by KarlDorogy — CHANGES_REQUESTED** [review]
Move the png files you use into the assets folder pls and update ur imports accordingly. Also idk why the amplify folder got renamed to amplify-backup for some reason (I assume u can just rename it back using a git rename command). Also, Why is the homepage being added in this request when its not finished?

**Comment by To-m-L** [comment]
> Move the png files you use into the assets folder pls and update ur imports accordingly. Also idk why the amplify folder got renamed to amplify-backup for some reason (I assume u can just rename it back using a git rename command). Also, Why is the homepage being added in this request when its not finished?
1. what's the point of having folders for each page if it will just be a single js file inside
2. It looks like Douglas committed and pushed to the wrong branch

**Comment by KarlDorogy** [comment]
It's good/common practice to have an assets folder for application development and to have an organized folder/file structure. Also, we will most likely be adding a test js file for each page folder similar to the App.test.js file that came with the initial project creation so we can test the front end for a specific page.

**Review by DouglasChafee — CHANGES_REQUESTED** [review]
ill resolve the homepage conflicts locally before pushing, not sure why its included. I agree the images should be in an asset folder. The page itself looks good.

**Pull request closed without merging**
