### PR TITLE
Landing

### PR DESCRIPTION
**Pull request by KarlDorogy**
# Description

Please include a summary of the changes and issues that were fixed. Please also include relevant context. List any dependencies that are required for this change.

Fixes # (issue)

- Added pull_request_tempalte.md to github for future standardized pull requests
- Added Landing Page UI
- Created a generalized animated button component for future UI use within /components directory.
- Fixed the navigation bar sign-in button so that it changes to white when hovered over.
- Fixed the navigation bar text page links with a bottom-line animation when clicked upon.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# (If Applicable) How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration

No Test Required ATM

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by To-m-L** [comment]
Looks good

**Review by JoshQU — APPROVED** [review]
Looks good. New review template works great.

**Review by BriggsFisher — APPROVED** [review]
Good changes, I will make sure to use the new template

**Comment by DouglasChafee** [comment]
looks good, i appreciate the template too

**Review by DouglasChafee — APPROVED** [review]

**Pull request merged**
